export const SKILLS = [
    "HTML",
    "CSS",
    "Java",
    "JavaScript",
    "React JS",
    "React Native",
    "Redux",
    "Node.js",
    "Express",
    "MongoDB",
    "MySQL",
    "Python",
    "Django",
    "Flask",
    "PostgreSQL",
    "SQL",
    "Git",
    "GitHub",
    "GitLab",
    "GitFlow",
    "GitHub Flow",
    "GitLab Flow",
    "GitKraken",
    "Google Cloud",
    "AWS",
    "Heroku",
    "Netlify",
    "Firebase",
    "Firestore",
    "Firebase Auth",
    "Firebase Storage",
    "Firebase Cloud Functions",
    "Firebase Cloud Firestore",
    "Firebase Cloud Messaging",
    "Firebase Cloud Storage",
]